services:
  web-api-app: #Название сервиса
    image: asp-api-app
    build: 
      context: .
      dockerfile: WebApiApp/Dockerfile
    ports:
      - "5687:5687" # Пробрасываем порты 5687 контейнера на порт 5687 хоста
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Устанавливаем переменную окружения ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/src
  web-client-app:
    image: asp-client-app
    build: 
      context: ./WebClientApp
#      dockerfile: ./WebClientApp/Dockerfile
    working_dir: /app
    ports:
      - "5272:5272" # Пробрасываем порты 5272 контейнера на порт 5272 хоста
    volumes:
      - ./WebClientApp:/app
      - /app/node_modules